// apps/web/src/lib/api/index.ts — Dev 5 [P2-INT-02]
export {
  apiFetch,
  authApi,
  studySetApi,
  flashcardApi,
  folderApi,
  healthApi,
  fetchHealth,
  ApiError,
} from "./client";
export type {
  User,
  AuthResponse,
  StudySet,
  Flashcard,
  DraftCard,
  FolderSummary,
  FolderDetail,
  CreateFolderInput,
  UpdateFolderInput,
  LearningMode,
  LearningProgress,
  StudySetListParams,
  StudySetListResult,
  BulkFlashcardItem,
  BulkSaveResult,
  CreateStudySetPayload,
  UpdateStudySetPayload,
  CreateFlashcardPayload,
  UpdateFlashcardPayload,
  ServiceHealth,
} from "./client";
